### ISSUE TITLE
프로젝트 진행 시 궁금한 사항을 이슈로 만들었습니다. #1

### ISSUE THREAD

**Issue by hanurii** [Hydronium-ion/Rare-Server#32]
#### 서로 알고 있는 프로그래밍 지식의 차이가 존재합니다.
- PR 시 서로 리뷰를 해주면서 각자 궁금했던 점을 여기에 적고 공부한 내용을 추가합니다. 
- 좋은 지식 형성에 도움을 줄 수 있도록 서로 도와줍시다!

**Comment by hanurii** [comment]
[궁금했던 점]
1. @MappedSuperclass 랑 @EntityListeners 란?
2. @CreatedDate 란
3. 제네릭 사용법
4. @GeneratedValue(strategy = GenerationType.IDENTITY) 란?
5. @AllArgs ... @NoArgs ... @RequireArgs ... 3개의 역할과 사용법
6. @JsonPropertyOrder 란?
7. GlobalExceptionHandler 와 ApiError

**Comment by 102092** [comment]
어노테이션에 대해서 제가 1,2번을 정리해보겠습니당

**Comment by 102092** [comment]
### lombok
- 5번
- https://cheese10yun.github.io/lombok/
- https://partnerjun.tistory.com/54

**Comment by 102092** [comment]
## 1,2번 어노테이션에 대해 정리
- https://www.notion.so/JPA-Annotation-505e0a882dd8488fbe9b42206e4f7d53

**Comment by hanurii** [comment]
1,2번 : https://www.notion.so/han95210/Annotation-981c64bdcf4349028baa9a10905c5a46#666180ad76774cfab206888c10d42471
3번 : 공부하는 대로 추가할게요!
4번 : https://www.notion.so/han95210/Annotation-981c64bdcf4349028baa9a10905c5a46#eacda9da8a8441739b9e2781b4a6ec69
5번 : https://www.notion.so/han95210/Annotation-981c64bdcf4349028baa9a10905c5a46#7f843aef60154e8db1cd8742b81855d0
6번 : https://www.notion.so/han95210/Annotation-981c64bdcf4349028baa9a10905c5a46#ffb1719cdab14d20b3596d390494e951
7번 : https://www.notion.so/han95210/GlobalExceptionHandler-ApiError-90bfc0114fd74cc9ad8f290777deb4d3 (아직 공부하고 있습니다)

**Comment by 102092** [comment]
https://github.com/Hydronium-ion/Rare-Server/wiki
- 위키 메인 페이지에 정리가 완료된것을 채워보면 좋을듯 합니다!
