### ISSUE TITLE
7월 4주차 정리 

### ISSUE THREAD

**Issue by 102092** [Hydronium-ion/Rare-Server#36]
#### 이슈 작성 이유
- 한주간 개발하면서, 궁금하거나 정리가 필요한 사항을 여기에 추가함
- 매주 금요일 정리예정

#### 목록
- [x] JPA delete 메서드 작동 방식에 대해 정리
- [x] JPA pagination 사용법
- [x] AWS Lambda, AWS CloudWatch 필요한 IAM권한, 알게된 내용에 대해

**Comment by 102092** [comment]
https://www.notion.so/EC2-auto-stop-start-e8861199d9f940faa99bc5b256b199b3

**Comment by hanurii** [comment]
JPA pagination 사용법
- https://www.notion.so/han95210/Spring-Data-JPA-API-b0603a28e5ff4f809ff70013362a7014
