### ISSUE TITLE
도메인과 테이블 설계

### ISSUE THREAD

**Issue by hanurii** [Hydronium-ion/Rare-Server#6]
### 이슈 작성 이유
- 엔티티 생성을 하기 전에 서비스 전체 모델을 Design 할 필요가 있다.
- 엔티티, 테이블 설계는 가장 기본적인 기능부터 넣고 필요할 때 설계를 바꾼다.

### 메인 페이지 스토리
 1. 유저가 접속을 하면 좋아요순으로 블로그 글이 보인다
 2. 유저가 검색버튼을 클릭하면 검색창이 새로뜨고 태그를 입력해서 원하는 검색결과를 얻을수 있다
 3. 유저는 메인페이지를 최신순으로도 볼수있다
 4. 유저가 블로그 글을 방문하면 조회수가 올라간다
 5. 유저는 헤더영역의 본인 아이콘을 클릭하면 여러 옵션을 볼수있다
 6. 유저는 팔로우한 사람이 글을쓰면 알람을 받을수있다 (나중에 구현)

**Comment by hanurii** [comment]
![주석 2020-07-14 123319](https://user-images.githubusercontent.com/38041572/87380816-3f0d6a00-c5ce-11ea-9ebe-a5e5c408be6a.png)

1차 DB 설계입니다

**Comment by 102092** [comment]
![image](https://user-images.githubusercontent.com/22140570/87522427-955ad580-c6c0-11ea-9cff-c26203846b98.png)

- 현재 메인 스토리에 해당하는 도메인 들로만 구성하려 했습니다.
- 해당 Entity에 어떤 멤버변수들이 필요할지는 이야기해보면 좋을듯 합니다~ 위에 잘 정리해 놓으셨네용... 👍

**Comment by hanurii** [comment]
![blogERDexample1](https://user-images.githubusercontent.com/38041572/87631617-abc16980-c772-11ea-8c27-b71311d23678.png)
![blogERDexample2](https://user-images.githubusercontent.com/38041572/87631621-acf29680-c772-11ea-9208-86c265b8dde8.png)
![blogERDexample3](https://user-images.githubusercontent.com/38041572/87631624-acf29680-c772-11ea-9f85-6bc11c718f5e.png)
![blogERDexample4](https://user-images.githubusercontent.com/38041572/87631626-ad8b2d00-c772-11ea-85df-8049c1f8f76d.png)

**Comment by 102092** [comment]
![image](https://user-images.githubusercontent.com/22140570/87634320-f5608300-c777-11ea-8ac5-82cf7d95d333.png)
